In [1]:
import pandas as pd

In [3]:
df = pd.read_clipboard()

In [7]:
df

,,,image_name,psnr_oi_ai,psnr_oi_oo,psnr_ai_ao,psnr_aip_aop,bpp_oc,bpp_ac,time_taken,psnr_relative_loss
0,0001,51.714214,35.238274,27.515215,13.328210,0.881456,0.882304,0,days,00:00:31.826807,-21.916677
1,0002,53.530602,34.199881,28.833095,13.154697,1.139532,1.139817,0,days,00:00:03.095608,-15.692409
2,0003,53.135887,33.718651,28.734452,14.747389,1.184537,1.186153,0,days,00:00:21.454124,-14.781729
3,0004,52.714989,39.813108,30.449648,15.496181,0.441229,0.457283,0,days,00:00:19.080663,-23.518535
4,0005,52.737442,36.155082,27.968661,12.746447,0.939688,0.940279,0,days,00:00:16.274721,-22.642516
5,0006,51.692219,38.872837,29.405301,13.514724,0.462121,0.463155,0,days,00:15:39.716509,-24.355146
6,0007,52.119308,32.011065,26.894833,13.331461,1.508285,1.508785,0,days,00:00:21.348385,-15.982699
7,0008,54.320534,35.124360,28.539012,13.950552,0.819710,0.821093,0,days,00:05:26.953739,-18.748663
8,0009,52.633652,35.808416,28.963815,13.605459,1.073901,1.074424,0,days,00:00:12.277104,-19.114503
9,0010,53.206612,36.127975,29.583631,14.269848,0.752986,0.753856,0,days,00:00:05.608149,-18.114341
10,Average,52.780546,35.706965,28.688766,13.814497,0.920345,0.922715,0,days,00:02:19.763580900,-19.486722

In [10]:
df.to_csv('div2k_logexp.csv', sep=';')